robot:
  gap: 10.0
  gap_ignore: 5.0
  amount: 10
  delay: 0.1 #s
exchange:
  client_id: HVyWOxj4
  client_secret: 9lg-QCb19mXKOkQRrYYB3ig8AJdgOA8EOjeGhi6EiWI
  uri: wss://test.deribit.com/ws/api/v2
  instrument: BTC-PERPETUAL