robot:
  gap: 10.0
  gap_ignore: 5.0
  amount: 10
  delay: 0.1 #s
exchange:
  client_id: HVyWOxj4
  client_secret: i3OZ_-cjSUOqpkA6ZkROPqNgJ9eRr128c_w1Aom6wec
  uri: wss://test.deribit.com/ws/api/v2
  instrument: BTC-PERPETUAL